language: node_js
node_js:
- 8
script: npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
branches:
  only:
  - master
notifications:
  slack:
    secure: Ho4rTXU2Db5337rsZIyyBzOFMgjl9UfrbiBLn/KMopMWw4UQ2LEsjVhp/LuqTDqQ9nETEbwJ0UUAfsDZvNrbEOsybXGwhhR9H5PONRqS+M8IXNS8wvOIjxMGfxgo6GZfaT2ZpXVkcfJYoQgp2quqMm7nWzHjjjcn4vi/MXEeQcx3f3ZX2F1pU2RRqfPP6HbBat3O4yM6MowqE6LTI9eYO4dHHT+gJfS6RGDVLAoZYQH2xj0AuCBMA88JuBphFHT5uKJf0IF8EGb2R+3DZGpGG/CX9tv840DYaZTPdyj0Ee8GocK8J14VAwraAYgK1973T3h/j9G7ND2hZd31zfrLa9n+20uvkGTWmghuG3xXUCJFGmahBZfxXWHl2RtUSXErZ9EOKZtNfuQadESS6C7JDVb/vPuy70SKHxB/HhOcJio4rmTZAFvUoUc8JFy4pLCYyhWc5GZrF/F/QtDcgN/+ZufAFNBeDS2QO/ljggqbqVCKT3oc1BZfwRpX+tzWWjkLnyzB6CP7M4noS2Rp6M+f2muYIrrmcEFC14PQ2B9uQByEg+QdY7Wj/4lsFldzWaYgrerC7OSu+hHOQkBpOAZpDB/lP9ZhKmnaBxqxD2Qe27deWKlyB56Bz7JWp8/2ZS0LsKfg8aRvARI4kdbDDOlKFvFf5Kx58IQHUpRJUFu0BaM=
