language: node_js
node_js:
- 12
script:
- npm install -g serverless
- npm run deploy:prod
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  local_dir: dist
  on:
    branch: master
branches:
  only:
  - master
notifications:
  slack:
    secure: tKEbbOaiarDXsq30NwZD5hT7t4ehnPtHnEiZGE76lXKjP11Z/VyGmk+ZrrfVibyYwPit/2ZqHOxxOW/pW/Vs7grnxjdwXIQKepduV10cOWKik9Yd9srUtI2othH92SQLgnRNai9v2QhNXM1M/R/U65H/Z1cq+JQdGUoHLMwWd1T25MOUBBHwKkgsOmBeyreuxxpLDgDWBG9YJJhYgbf/2k5r3qiwwiLbfbPIJByTmfOc3EPUb8FNZ6U+nYAo3EtNgXB2ijDQOBp1QcRfy5thqdHHa52eXNg38K5TAdS0GtKpf0XslFK07SIQMnY5PPde+pwv3AgCRYvajd+h3J1kV+dtPNWaGylDTF5O7+iIPQzZQirSWXlRbT1ay2rsSe5ONtkheRw4VtBExB4pb9jlNuBjHKMpyJBe5A+JMooiF3lzx4hm9/EelmsI5akWRGXKY5N+zlEDJRxFt7gy+otwqBe3XIizlUaLHSc4t+jrMM99heqKlzXeXDURCqgdN60vLF+gWr3JBaM7EdXj2hIZOlgIeu+zGX5mTMfWt4q5C3ArlsWqtdK3agkxlwogpr4pBMPLF1zNQmOTEiElQWyEqFkGP94krRNzgB3dmvwdTeRNeOMLm/lrFHwjQEwFyBUKpfEV791y9qj3RIEf7VvWvbOPb29f8ly4iIZhK6w2Wpo=
env:
  global:
  - secure: mSphtOv52V397pnbgX+fEj0pwI8LwH44cIPQhAVLyWizOufeIqKoLx+EGYRH05XRISSSOvSjrwnaE5Jqorf1H5hu937xkpMe4W3PfJIh7KohFv3hChZkwnNbZVKyt0xwgdRTcT9g0W/085066PuvnTv0ZzYyv3TvCflvjnnOG8mStm2qGPzweLmxtwowEVCs0xDdzKAbA2Zh/UW+qvO5KNK6pJzTw/DZoyT23Dxfn7o4GTZghq5/tc+XySUGqclW0pt9MsLxYqbsdQyiwsUxY4E4pqVr7cq8Ai0ECvlFXCvysMKo6vNIBInoxRYWJHRrV9pDziVGG06FSJlokEkXhtLy3PpXFWzNd2TClTQ6aaJsUjdXrz9APvErTDdZmeeIiOpo0gD3icXF00ZwyevCkxafgGTdn/hzgf8N2kl/3HXemuF2KgBvnWNT79PtBuUW9H8z9MSzG/2t3hweINCdeW1cyV6o8+s0BaTQz6c5vZHFVZtmmOkhGm3ObC4tpgm6XbT3+2S3MzXbzAeClhtdFocG0NXwreVza4JY8rFgLGRhPWAtzlOHdxztqmGjnQWRYP8KlZ7XrEOfaz7nIesBG3Vgud9ezE/0wTPmQa9O4g9oKR71XQf4qt5ASIeuK3qDO4ca5poTFC+4LvOjYOhIGP6vkhJjziqPtUiTskWNMzI=
  - secure: JU6Jw4w7h8OAObuqLOK/rLhRJadgnjj1Larrl8wQkUPH/IR7kDkOxqvMZZrdIBAxEm3fOhILIKcNnJab1JpTDNHWD6pqH0ui81XkGtGJNSRtONyNAgs7FG6WG8VLS5ZP3XIee1O9ZSduJbmUezZnFGpC+Kjz0M9GyYpG0tQLcVbUoEM23ck10iDOSloPhrMvwClOLTJ+nE+qHKKVKxVywzGUDdLljUacC7meBkKUWcooiBjduclIlDaCIajTXknJ+/ttlZ+VgOZnrq5p6+WE6xO8oCPVbyISCzu3TBYkDYFL8ChfGjcab/kHNxHhi1SsKuTZ/1UmG1I9V/ZpzoAUC4o7TndZF3fIoXPP9KaeI/QdKdi/vz+CFccsNuOFm9l6ieJMsaDpT61sZjhbygGaYNY0rTBodUdYJQulS7BsFqv7TWw5qQDBl2LqvseIDPWfZklUGNF1In+s8hxSYNnG+uVdHFBUZLHfumu8iOTalRThfVRnVoxbihnxgOtrcBlzZFHMa0wP7H+idUfpLhu90jpMsFUJBXMddSErQ2wKbPMCu/YDsW/QMTDZn9k2GvoTCAs+U2l/daTEHImSsHL0XsjgBWeoqpx92OfuD++9HURXkJ7sK83w5ekzWKYNcjzCx6FuRD0jNHM8rWvJgs7ZY9S3LUQ+5bRBUn9x3aJT0Vs=
