name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Node.js
      uses: actions/setup-node@v1.1.0
    - name: Serverless Framework
      uses: serverless/github-action@v1.53.0
    - name: Setup node_modules
      run: npm install
    - name: Deploy server
      run: npm run deploy:prod
    - name: Build pages
      run: npm run build
    - name: Deploy pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: dist/
